# Site settings
title: Angelia
header-img: img/home-bg.jpg
email: angeliawang@me.com
description: "Personal Blog"
baseurl: ""
url: "https://angeliaw.github.com"
twitter_username: angeliawl
github_username:  angeliaw
facebook_username:  wlangelia

# Build settings
markdown: rdiscount
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments
permalink: pretty
paginate: 100 # Posts per page on the blog index
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Navigation
navigation:
- text: About
  url: /about/
- text: Blog
  url: /blog/
- text: Resume
  url: /resume/
- text: Links
  url: /links/
- text: Category
  url: /category/
- text: Tags
  url: /tags/
- text: Archive
  url: /archive/

# Author Details
author:         Angelia
linkedin:       'http://www.linkedin.com'
twitter:        'https://twitter.com/angeliawl'
facebook:       'https://www.facebook.com/wlangelia'
gplus:          ''
github:         'http://www.github.com/angeliaw'
weibo:          'http://weibo.com/37767312'
wechat:         'https://wx.qq.com'

# Google Analytics
gahandler: 'UA-58032801-1'

# Disqus
disqushandler: angeliaw

# Blog Configurations
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.9
