auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: angeliaw.github.com
url: http://angeliaw.github.com 
feed: /atom.xml
author_info: <a href="http://angeliaw.github.com/">Angelia</a>
