name: Angelia
author: Angelia
markdown: rdiscount
highlighter: pygments 
baseurl: 
description: 
github: http://www.github.com/angeliaw
twitter: https://twitter.com/angeliawl
facebook: https://www.facebook.com/wlangelia
linkedin: http://www.linkedin.com
weibo: http://weibo.com/37767312
disqus: diqus-angeliaw
